# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
vacation = pd.read_csv("weather_data_df.csv")
vacation_df = pd.DataFrame(vacation)
vacation_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Deputatsky,69.30,139.90,62.78,43,100,13.27,RU,1595135636
1,Bluff,-46.60,168.33,39.00,83,26,3.00,NZ,1595135621
2,Punta Arenas,-53.15,-70.92,33.80,80,99,18.34,CL,1595135464
3,Hobart,-42.88,147.33,60.01,54,40,5.82,AU,1595135525
4,Camacha,33.08,-16.33,69.80,83,40,11.41,PT,1595135996
5,Turukhansk,65.82,87.98,61.03,52,1,3.62,RU,1595135997
6,Ushuaia,-54.80,-68.30,30.20,100,90,8.05,AR,1595135600
7,Upernavik,72.79,-56.15,46.65,59,16,4.03,GL,1595135639
8,Atuona,-9.80,-139.03,79.07,79,44,16.73,PF,1595135615
9,Ondjiva,-17.07,15.73,43.75,60,0,6.55,AO,1595135998

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
gmaps.configure(api_key=g_key)

In [17]:
fig = gmaps.figure()

locations = vacation_df[["Lat", "Lng"]].astype(float)

heat_layer = gmaps.heatmap_layer(locations, weights=vacation_df["Humidity"], 
                                 dissipating = False, max_intensity=100,
                                 point_radius = 2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [28]:
# Temperature between 80 and 90
# Wind speed < 20
# Cloudiness < 30
# Humidity < 50

ideal_df = vacation_df.loc[vacation_df["Max Temp"] >= 80.00, :]
ideal_df = ideal_df.loc[ideal_df["Max Temp"] <= 90, :]
ideal_df = ideal_df.loc[ideal_df["Wind Speed"] < 20, :]
ideal_df = ideal_df.loc[ideal_df["Cloudiness"] < 30, :]
ideal_df = ideal_df.loc[ideal_df["Humidity"] < 50, :]
ideal_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
73,Mount Isa,-20.73,139.50,82.40,10,0,10.29,AU,1595135613
157,Birjand,32.87,59.22,82.40,14,0,16.11,IR,1595136037
232,Akhtubinsk,48.28,46.17,82.02,43,0,13.00,RU,1595136058
302,Zhangye,38.93,100.45,85.91,13,22,5.86,CN,1595135662
341,Port Keats,-14.25,129.55,82.74,43,10,9.08,AU,1595136094
354,Adrar,20.50,-10.07,89.64,26,26,12.80,MR,1595135642
430,Semnan,35.57,53.40,87.48,17,0,6.11,IR,1595136122
438,Kununurra,-15.77,128.73,89.60,13,25,5.82,AU,1595136124
472,Mukhen,48.10,136.10,89.29,49,21,4.74,RU,1595136134
476,Ubari,26.59,12.78,83.98,26,2,12.37,LY,1595135619
480,Murgab,37.50,61.97,89.60,25,0,11.41,TM,1595136137
530,Atambua,-9.11,124.89,83.17,45,0,1.19,ID,1595135631
541,Derzhavīnsk,51.10,66.32,87.03,36,0,13.89,KZ,1595136157

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure